name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every day at midnight UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure Git to allow unrelated histories
        run: |
          git config --global pull.rebase false
          git config --global fetch.recurseSubmodules on-demand

      - name: Update submodules
        run: |
          git submodule update --remote --merge || git submodule update --remote --merge --strategy-option=theirs
          git add .
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
