name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every day at midnight UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule foreach --recursive '
            git fetch origin main;
            git checkout main;
            git pull origin main
          '
          git add .
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
